import React from 'react';
import { 
  MousePointer2, 
  Pen, 
  Highlighter, 
  Minus, 
  Square, 
  Circle, 
  Type, 
  Eraser, 
  Upload, 
  Download, 
  Save, 
  Plus, 
  Trash2,
  Undo2,
  Redo2,
  Image as ImageIcon,
  FileText,
  Mic,
  Settings,
  ScanText,
  Sparkles,
  Volume2,
  Globe,
  Hand,
  Languages,
  Loader2,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignRight,
  List,
  Palette,
  Sliders,
  ChevronDown,
  Copy,
  Layers,
  Sun,
  ClipboardPaste,
  Files,
  Zap,
  X,
  ArrowUp,
  ArrowDown,
  MoveHorizontal,
  MoveVertical,
  Play,
  ArrowUpToLine,
  ArrowDownToLine,
  ArrowLeftToLine,
  ArrowRightToLine,
  ListOrdered,
  Group,
  Ungroup,
  Move,
  Shapes,
  Table as TableIcon,
  Diamond,
  ArrowRight,
  Calculator,
  Edit
} from 'lucide-react';

export const Icons = {
  Edit: Edit,
  Calculator: Calculator,
  Move: Move,
  Group: Group,
  Ungroup: Ungroup,
  Select: MousePointer2,
  Hand: Hand,
  Pen: Pen,
  Highlighter: Highlighter,
  Line: Minus,
  Rect: Square,
  Circle: Circle,
  Text: Type,
  Eraser: Eraser,
  Upload: Upload,
  Download: Download,
  Save: Save,
  Plus: Plus,
  Trash: Trash2,
  Undo: Undo2,
  Redo: Redo2,
  Image: ImageIcon,
  File: FileText,
  Mic: Mic,
  Settings: Settings,
  ScanText: ScanText,
  Sparkles: Sparkles,
  Volume: Volume2,
  Globe: Globe,
  Languages: Languages,
  Loader: Loader2,
  Shapes: Shapes,
  TableIcon: TableIcon,
  Diamond: Diamond,
  ArrowRight: ArrowRight,
  
  // Text Formatting and Styling Icons
  Bold: Bold,
  Italic: Italic,
  Underline: Underline,
  Strikethrough: Strikethrough,
  AlignLeft: AlignLeft,
  AlignCenter: AlignCenter,
  AlignRight: AlignRight,
  List: List,
  Palette: Palette,
  Sliders: Sliders,
  ChevronDown: ChevronDown,
  Copy: Copy,
  Layers: Layers,
  Sun: Sun,
  ClipboardPaste: ClipboardPaste,
  Files: Files,
  Zap: Zap,
  X: X,
  ArrowUp: ArrowUp,
  ArrowDown: ArrowDown,
  MoveHorizontal: MoveHorizontal,
  MoveVertical: MoveVertical,
  Play: Play,
  ArrowUpToLine: ArrowUpToLine,
  ArrowDownToLine: ArrowDownToLine,
  ArrowLeftToLine: ArrowLeftToLine,
  ArrowRightToLine: ArrowRightToLine,
  ListOrdered: ListOrdered
};

export type IconName = keyof typeof Icons;